### PR TITLE
Yet another PG 11 problem: postgresBeginForeignModify needs PlanState.

### PR DESCRIPTION
**Pull request by arssher**

### CODE REVIEW

**Comment by arssher** [comment]
(immediately revealed by shardman's tests)

**Comment by funbringer** [comment]
I'll look into this tomorrow. We should add a pythonic test for this as well.

**Comment by arssher** [comment]
Actually the test is already there, it's just usually not executed due to missing `postgres_fdw`.

**Comment by funbringer** [comment]
I pushed roughly the same piece of code to `next`. Thanks!

**Pull request closed without merging**
