### PR TITLE
Add Debian packaging

### PR DESCRIPTION
**Pull request by saaros**
`make deb9.5` to build a postgresql-9.5-pathman package.

### CODE REVIEW

**Comment by funbringer** [comment]
Hi @saaros,

Thank you for being interested in our project and for wanting to help us. Nevertheless, I'm doubtful about this feature. We already have a PostgreSQL distro which includes the latest stable release of pg_pathman, why would we need to add a specific Makefile rule to build a debian package?

**Comment by saaros** [comment]
I'd be happy to use existing packages, but didn't find any so I rolled my own packaging scripts.  Could the README be updated to point to existing binaries?

**Comment by funbringer** [comment]
@saaros 

Unfortunately we don't provide separate packages for extensions at the moment. This will probably change in future.

**Comment by saaros** [comment]
In that case it sounds like providing packaging scripts would be useful for people wanting to use this extension in their systems.

**Comment by zilder** [comment]
Hi @saaros,
Thank you for your pull request. We've had a discussion about it and decided not to merge it into this repo. But it is a good idea to have packaging scripts for different platforms, so we'll create a separate repository which will contain scripts for building and packaging pg_pathman. And we'll put a download link to our site as well.

**Comment by saaros** [comment]
Ok, I guess that works as well, although to me it feels like it would be much easier for users of these extensions to get the packaging scripts with the rest of the repo - in case they're interested in one particular extensions instead of everything you have.  Anyway, feel free to close this PR if you don't think it should be merged.  Thanks!

**Pull request closed without merging**
